data <- read.table("household_power_consumption.txt", header=TRUE, sep=";", na.strings="?")
data$Date <- as.Date(data$Date, format="%d/%m/%Y")
data <- subset(data, Date >= "2007-02-01" & Date <= "2007-02-02")
data$DateTime <- strptime(paste(data$Date, data$Time), format="%Y-%m-%d %H:%M:%S")
png("plot4.png", width=480, height=480)
par(mfrow=c(2,2))
plot(data$DateTime, as.numeric(data$Global_active_power), type="l", xlab="", ylab="Global Active Power")
plot(data$DateTime, as.numeric(data$Voltage), type="l", xlab="datetime", ylab="Voltage")
plot(data$DateTime, as.numeric(data$Sub_metering_1), type="l", xlab="", ylab="Energy sub metering")
lines(data$DateTime, as.numeric(data$Sub_metering_2), col="red")
lines(data$DateTime, as.numeric(data$Sub_metering_3), col="blue")
legend("topright", bty="n", lty=1, col=c("black","red","blue"), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(data$DateTime, as.numeric(data$Global_reactive_power), type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()
